### ISSUE TITLE
Refactor: Move CORS to middleware folder 

### ISSUE THREAD

**Issue by BeauBouchard** [Crucible-Standard/obiter-dictum#99]
# Description

Move the CORS middleware from the `app.js` main file and make an expandable folder that it resides in as `cors.js`.

### Tasks

* [ ] new file `middleware/cors.js`
* [ ] new file `middleware/index.js`
* [ ] refactor `app.js` to load previous cors middleware from new file
* [ ] clean up
* [ ] tests
